### ISSUE TITLE
can't install/enable nbextension

### ISSUE THREAD

**Issue by shelmz** [atiro/ipyiiif#1]
this happens during installation, no matter if directly with pip or as development- via npm:

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "$HOME.local/lib/python3.8/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "$HOME.local/lib/python3.8/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.8/dist-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "$HOME.local/lib/python3.8/site-packages/jupyter_core/application.py", line 253, in start
    self.subapp.start()
  File "/usr/local/lib/python3.8/dist-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/usr/local/lib/python3.8/dist-packages/notebook/nbextensions.py", line 682, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/usr/local/lib/python3.8/dist-packages/notebook/nbextensions.py", line 206, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.8/dist-packages/notebook/nbextensions.py", line 1119, in _get_nbextension_metadata
    raise KeyError('The Python module {} is not a valid nbextension, '
KeyError: 'The Python module iiif is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
```

is this package supposed to be working with the current python and pip versions?

**Comment by atiro** [comment]
Sorry @shelmz I've just seen this. No, it's very very out of date, I just haven't had the time/project to get back onto this yet. Was rather hopeful someone would have come up with a better implementation by now...
